### PR TITLE
Fix the get state endpoint, allowing for player UUID not to be provided

### LINKED ISSUE #51: Fix the get state endpoint not to require the player_uuid
The UUID validation I implemented yesterday checks whether the `player_uuid` in the get state endpoint is a valid UUID. However, in that endpoint, the player UUID is optional so `player_uuid` does not need to be a valid UUID (rather, it can be the default value: an empty string).

### PR DESCRIPTION
**Pull request by maciej-pomykala**
Closes #51

### CODE REVIEW

**Comment by adrian-golian** [comment]
This is a general gripe about R, but I would love to replace all instances of
```
if (something) {
  lots
  of
  code
}
elseif ( !something) {
return error code
}
```
with this:
```
if (!something) {
return error code
}
lots
of
code
```

We doing an ` elseif ` where `else ` would be enough (but it’s impossible to know which ` if ` it’s for, so you need the elseif to inform).
I’ve tried to write sensible control flow in R, but `return ` doesn’t seem to stop a function’s execution (!) and so I guess you end up with abuse like this.

File: api/endpoints.R [hunk 1]
```diff
@@ -200,7 +200,7 @@ function(game_uuid, player_uuid = "", res, round = -1) {
   } else if (!game_uuid_valid) {
     res$status <- 400
     list(error = "Invalid game UUID")
-  } else if (!player_uuid_valid) {
+  } else if (!(player_uuid == "" | player_uuid_valid)) {
```
Comment (adrian-golian) [inline api/endpoints.R:203]: How about applying some deMorgan here for fewer nested brackets?
```
if (!player_uuid == "" & !player_uuid_valid)
```

Comment (maciej-pomykala) [reply api/endpoints.R:203]: On one hand this could look nicer, on the other hand this would not match the exact specification fo teh condition in the original if, so would reduce clarity, don't you agree?

Comment (adrian-golian) [reply api/endpoints.R:203]: What's the "original `if`"?

Comment (maciej-pomykala) [reply api/endpoints.R:203]: `if (game_uuid_valid & (player_uuid == "" | player_uuid_valid))`

Comment (maciej-pomykala) [reply api/endpoints.R:203]: Basically, the `else if` is associated with a preceding `if` and it would be good for the inverted conditions in these two to be specified in a similar way

Comment (adrian-golian) [reply api/endpoints.R:203]: If you intend to keep and use those two conditions together then make `player_uuid_valid_or_empty`.
I assumed there's only one spot to use this in when I suggested `player_uuid == "" | player_uuid_valid`. You're clearly using the same condition multiple times and are also intending to 
> match the exact specification fo the condition
then just put it in a variable.

Comment (adrian-golian) [reply api/endpoints.R:203]: Otherwise, I'd say drop the idea of 

> match the exact specification fo the condition

and just simplify the condition to `notX and notY`.

Comment (maciej-pomykala) [reply api/endpoints.R]: Lol ok, done
